name: Build and test

on:
  push:
    branches:
      - "master"
    paths:
      - "src/main/java/**/*.java"
      - "src/test/java/**/*.java"
      - "!.editorconfig"
      - "!.gitattributes"
      - "!.gitignore"
      - "!README.md"
      - "!README"
      - "!LICENSE"
      - "!COPYING"
      - "build.gradle.kts"
      - "settings.gradle.kts"
      - "gradle.properties"
  pull_request:
    branches:
      - "master"
    paths:
      - "src/main/java/**/*.java"
      - "src/test/java/**/*.java"
      - "!.editorconfig"
      - "!.gitattributes"
      - "!.gitignore"
      - "!README.md"
      - "!README"
      - "!LICENSE"
      - "!COPYING"
      - "build.gradle.kts"
      - "settings.gradle.kts"
      - "gradle.properties"
  workflow_dispatch:


defaults:
  run:
    shell: bash


jobs:
  build:
    name: Build (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    permissions:
      contents: read
      checks: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: corretto
          cache: "gradle"

      - run: ./gradlew build

      - uses: PineBale/jacoco-csv-summary@v1.0.1
        with:
          csv-file: ./build/reports/jacoco/test/jacocoTestReport.csv
          write-summary: true
          write-check: true
          check-name: Coverage (${{ matrix.os }})

      - uses: mikepenz/action-junit-report@v6.4.0
        if: ${{ success() || failure() }}
        with:
          report_paths: ./build/test-results/test/TEST-*.xml
          include_passed: true
          detailed_summary: true
          fail_on_failure: true
          require_tests: true
          check_name: Test Report
          check_title_template: '{{SUITE_NAME}} | {{TEST_NAME}}'
