name: Build and test

on:
  push:
    branches:
      - "master"
    paths:
      - "src/main/java/**/*.java"
      - "src/test/java/**/*.java"
      - "pom.xml"
      - "!.gitignore"
      - "!README.md"
      - "!README"
      - "!LICENSE"
      - "!COPYING"
  pull_request:
    branches:
      - "master"
    paths:
      - "src/main/java/**/*.java"
      - "src/test/java/**/*.java"
      - "pom.xml"
      - "!.gitignore"
      - "!README.md"
      - "!README"
      - "!LICENSE"
      - "!COPYING"
  workflow_dispatch:


defaults:
  run:
    shell: bash


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}
    permissions:
      contents: read
      checks: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v5
        with:
          java-version: 8
          distribution: corretto
          cache: "maven"

      - run: mvn -B -V -e -ntp -Dstyle.color=always clean verify

      - uses: mikepenz/action-junit-report@v6.4.0
        if: ${{ success() || failure() }}
        with:
          report_paths: ./target/surefire-reports/TEST-*.xml
          include_passed: true
          detailed_summary: true
          fail_on_failure: true
          require_tests: true
          check_name: Test Report (${{ matrix.os }})
          check_title_template: '{{SUITE_NAME}} | {{TEST_NAME}}'

      - uses: PineBale/jacoco-csv-summary@v1.0.1
        with:
          csv-file: ./target/jacoco-report/jacoco.csv
          write-summary: true
          write-check: true
          check-name: Jacoco (${{ matrix.os }})
